/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -i format_converter_options.ggo -F ./format_converter_options -a cmdLineOpts --output-dir=. 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "./format_converter_options.h"

const char *cmdLineOpts_purpose = "Provides ability to transform between adjacent data format versions";

const char *cmdLineOpts_usage = "Usage: NSCLDAQ Data Format Converter [OPTIONS]...";

const char *cmdLineOpts_versiontext = "";

const char *cmdLineOpts_description = "";

const char *cmdLineOpts_help[] = {
  "  -h, --help                 Print help and exit",
  "  -V, --version              Print version and exit",
  "  -s, --source=STRING        URL of source. Specifies either a ring buffer,\n                               file, or - for stdin  (default=`-')",
  "  -d, --sink=STRING          URL of sink. Specifies either a ring buffer, file,\n                               or - for stdout  (default=`-')",
  "  -i, --input-version=ENUM   Version of input data  (possible values=\"8\",\n                               \"10\", \"11\")",
  "  -o, --output-version=ENUM  Version of output data  (possible values=\"8\",\n                               \"10\", \"11\")",
  "  -p, --v8-size-policy=ENUM  Policy for interpreting buffer size  (possible\n                               values=\"Inclusive16BitWords\",\n                               \"Inclusive32BitWords\",\n                               \"Inclusive32BitBytes\", \"Exclusive16BitWords\"\n                               default=`Inclusive16BitWords')",
  "  -b, --v8-buffer-size=INT   Number of bytes in version 8 buffer\n                               (default=`8192')",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
  , ARG_ENUM
} cmdline_parser_arg_type;

static
void clear_given (struct cmdLineOpts *args_info);
static
void clear_args (struct cmdLineOpts *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct cmdLineOpts *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct cmdLineOpts *args_info, const char *prog_name, const char *additional_error);

const char *cmdline_parser_input_version_values[] = {"8", "10", "11", 0}; /*< Possible values for input-version. */
const char *cmdline_parser_output_version_values[] = {"8", "10", "11", 0}; /*< Possible values for output-version. */
const char *cmdline_parser_v8_size_policy_values[] = {"Inclusive16BitWords", "Inclusive32BitWords", "Inclusive32BitBytes", "Exclusive16BitWords", 0}; /*< Possible values for v8-size-policy. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct cmdLineOpts *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->source_given = 0 ;
  args_info->sink_given = 0 ;
  args_info->input_version_given = 0 ;
  args_info->output_version_given = 0 ;
  args_info->v8_size_policy_given = 0 ;
  args_info->v8_buffer_size_given = 0 ;
}

static
void clear_args (struct cmdLineOpts *args_info)
{
  FIX_UNUSED (args_info);
  args_info->source_arg = gengetopt_strdup ("-");
  args_info->source_orig = NULL;
  args_info->sink_arg = gengetopt_strdup ("-");
  args_info->sink_orig = NULL;
  args_info->input_version_arg = input_version__NULL;
  args_info->input_version_orig = NULL;
  args_info->output_version_arg = output_version__NULL;
  args_info->output_version_orig = NULL;
  args_info->v8_size_policy_arg = v8_size_policy_arg_Inclusive16BitWords;
  args_info->v8_size_policy_orig = NULL;
  args_info->v8_buffer_size_arg = 8192;
  args_info->v8_buffer_size_orig = NULL;
  
}

static
void init_args_info(struct cmdLineOpts *args_info)
{


  args_info->help_help = cmdLineOpts_help[0] ;
  args_info->version_help = cmdLineOpts_help[1] ;
  args_info->source_help = cmdLineOpts_help[2] ;
  args_info->sink_help = cmdLineOpts_help[3] ;
  args_info->input_version_help = cmdLineOpts_help[4] ;
  args_info->output_version_help = cmdLineOpts_help[5] ;
  args_info->v8_size_policy_help = cmdLineOpts_help[6] ;
  args_info->v8_buffer_size_help = cmdLineOpts_help[7] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(cmdLineOpts_versiontext) > 0)
    printf("\n%s\n", cmdLineOpts_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(cmdLineOpts_purpose) > 0)
    printf("\n%s\n", cmdLineOpts_purpose);

  if (strlen(cmdLineOpts_usage) > 0)
    printf("\n%s\n", cmdLineOpts_usage);

  printf("\n");

  if (strlen(cmdLineOpts_description) > 0)
    printf("%s\n\n", cmdLineOpts_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (cmdLineOpts_help[i])
    printf("%s\n", cmdLineOpts_help[i++]);
}

void
cmdline_parser_init (struct cmdLineOpts *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct cmdLineOpts *args_info)
{

  free_string_field (&(args_info->source_arg));
  free_string_field (&(args_info->source_orig));
  free_string_field (&(args_info->sink_arg));
  free_string_field (&(args_info->sink_orig));
  free_string_field (&(args_info->input_version_orig));
  free_string_field (&(args_info->output_version_orig));
  free_string_field (&(args_info->v8_size_policy_orig));
  free_string_field (&(args_info->v8_buffer_size_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct cmdLineOpts *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->source_given)
    write_into_file(outfile, "source", args_info->source_orig, 0);
  if (args_info->sink_given)
    write_into_file(outfile, "sink", args_info->sink_orig, 0);
  if (args_info->input_version_given)
    write_into_file(outfile, "input-version", args_info->input_version_orig, cmdline_parser_input_version_values);
  if (args_info->output_version_given)
    write_into_file(outfile, "output-version", args_info->output_version_orig, cmdline_parser_output_version_values);
  if (args_info->v8_size_policy_given)
    write_into_file(outfile, "v8-size-policy", args_info->v8_size_policy_orig, cmdline_parser_v8_size_policy_values);
  if (args_info->v8_buffer_size_given)
    write_into_file(outfile, "v8-buffer-size", args_info->v8_buffer_size_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct cmdLineOpts *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct cmdLineOpts *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct cmdLineOpts *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct cmdLineOpts *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct cmdLineOpts *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct cmdLineOpts *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct cmdLineOpts *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->input_version_given)
    {
      fprintf (stderr, "%s: '--input-version' ('-i') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (! args_info->output_version_given)
    {
      fprintf (stderr, "%s: '--output-version' ('-o') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct cmdLineOpts *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct cmdLineOpts local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "source",	1, NULL, 's' },
        { "sink",	1, NULL, 'd' },
        { "input-version",	1, NULL, 'i' },
        { "output-version",	1, NULL, 'o' },
        { "v8-size-policy",	1, NULL, 'p' },
        { "v8-buffer-size",	1, NULL, 'b' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVs:d:i:o:p:b:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 's':	/* URL of source. Specifies either a ring buffer, file, or - for stdin.  */
        
        
          if (update_arg( (void *)&(args_info->source_arg), 
               &(args_info->source_orig), &(args_info->source_given),
              &(local_args_info.source_given), optarg, 0, "-", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "source", 's',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* URL of sink. Specifies either a ring buffer, file, or - for stdout.  */
        
        
          if (update_arg( (void *)&(args_info->sink_arg), 
               &(args_info->sink_orig), &(args_info->sink_given),
              &(local_args_info.sink_given), optarg, 0, "-", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "sink", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* Version of input data.  */
        
        
          if (update_arg( (void *)&(args_info->input_version_arg), 
               &(args_info->input_version_orig), &(args_info->input_version_given),
              &(local_args_info.input_version_given), optarg, cmdline_parser_input_version_values, 0, ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "input-version", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Version of output data.  */
        
        
          if (update_arg( (void *)&(args_info->output_version_arg), 
               &(args_info->output_version_orig), &(args_info->output_version_given),
              &(local_args_info.output_version_given), optarg, cmdline_parser_output_version_values, 0, ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "output-version", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Policy for interpreting buffer size.  */
        
        
          if (update_arg( (void *)&(args_info->v8_size_policy_arg), 
               &(args_info->v8_size_policy_orig), &(args_info->v8_size_policy_given),
              &(local_args_info.v8_size_policy_given), optarg, cmdline_parser_v8_size_policy_values, "Inclusive16BitWords", ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "v8-size-policy", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Number of bytes in version 8 buffer.  */
        
        
          if (update_arg( (void *)&(args_info->v8_buffer_size_arg), 
               &(args_info->v8_buffer_size_orig), &(args_info->v8_buffer_size_given),
              &(local_args_info.v8_buffer_size_given), optarg, 0, "8192", ARG_INT,
              check_ambiguity, override, 0, 0,
              "v8-buffer-size", 'b',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
