/** @file format_converter_options.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef FORMAT_CONVERTER_OPTIONS_H
#define FORMAT_CONVERTER_OPTIONS_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "NSCLDAQ Data Format Converter"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "NSCLDAQ Data Format Converter"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "0.1"
#endif

enum enum_input_version { input_version__NULL = -1, input_version_arg_8 = 0, input_version_arg_10, input_version_arg_11 };
enum enum_output_version { output_version__NULL = -1, output_version_arg_8 = 0, output_version_arg_10, output_version_arg_11 };
enum enum_v8_size_policy { v8_size_policy__NULL = -1, v8_size_policy_arg_Inclusive16BitWords = 0, v8_size_policy_arg_Inclusive32BitWords, v8_size_policy_arg_Inclusive32BitBytes, v8_size_policy_arg_Exclusive16BitWords };

/** @brief Where the command line options are stored */
struct cmdLineOpts
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * source_arg;	/**< @brief URL of source. Specifies either a ring buffer, file, or - for stdin (default='-').  */
  char * source_orig;	/**< @brief URL of source. Specifies either a ring buffer, file, or - for stdin original value given at command line.  */
  const char *source_help; /**< @brief URL of source. Specifies either a ring buffer, file, or - for stdin help description.  */
  char * sink_arg;	/**< @brief URL of sink. Specifies either a ring buffer, file, or - for stdout (default='-').  */
  char * sink_orig;	/**< @brief URL of sink. Specifies either a ring buffer, file, or - for stdout original value given at command line.  */
  const char *sink_help; /**< @brief URL of sink. Specifies either a ring buffer, file, or - for stdout help description.  */
  enum enum_input_version input_version_arg;	/**< @brief Version of input data.  */
  char * input_version_orig;	/**< @brief Version of input data original value given at command line.  */
  const char *input_version_help; /**< @brief Version of input data help description.  */
  enum enum_output_version output_version_arg;	/**< @brief Version of output data.  */
  char * output_version_orig;	/**< @brief Version of output data original value given at command line.  */
  const char *output_version_help; /**< @brief Version of output data help description.  */
  enum enum_v8_size_policy v8_size_policy_arg;	/**< @brief Policy for interpreting buffer size (default='Inclusive16BitWords').  */
  char * v8_size_policy_orig;	/**< @brief Policy for interpreting buffer size original value given at command line.  */
  const char *v8_size_policy_help; /**< @brief Policy for interpreting buffer size help description.  */
  int v8_buffer_size_arg;	/**< @brief Number of bytes in version 8 buffer (default='8192').  */
  char * v8_buffer_size_orig;	/**< @brief Number of bytes in version 8 buffer original value given at command line.  */
  const char *v8_buffer_size_help; /**< @brief Number of bytes in version 8 buffer help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int source_given ;	/**< @brief Whether source was given.  */
  unsigned int sink_given ;	/**< @brief Whether sink was given.  */
  unsigned int input_version_given ;	/**< @brief Whether input-version was given.  */
  unsigned int output_version_given ;	/**< @brief Whether output-version was given.  */
  unsigned int v8_size_policy_given ;	/**< @brief Whether v8-size-policy was given.  */
  unsigned int v8_buffer_size_given ;	/**< @brief Whether v8-buffer-size was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure cmdLineOpts (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure cmdLineOpts (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *cmdLineOpts_purpose;
/** @brief the usage string of the program */
extern const char *cmdLineOpts_usage;
/** @brief the description string of the program */
extern const char *cmdLineOpts_description;
/** @brief all the lines making the help output */
extern const char *cmdLineOpts_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct cmdLineOpts *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct cmdLineOpts *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct cmdLineOpts *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct cmdLineOpts *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct cmdLineOpts *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed cmdLineOpts structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct cmdLineOpts *args_info);
/**
 * Deallocates the string fields of the cmdLineOpts structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct cmdLineOpts *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct cmdLineOpts *args_info,
  const char *prog_name);

extern const char *cmdline_parser_input_version_values[];  /**< @brief Possible values for input-version. */
extern const char *cmdline_parser_output_version_values[];  /**< @brief Possible values for output-version. */
extern const char *cmdline_parser_v8_size_policy_values[];  /**< @brief Possible values for v8-size-policy. */


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* FORMAT_CONVERTER_OPTIONS_H */
