BINDIR=/usr/opt/daq/7.4/bin
INCLUDEDIR=/usr/opt/daq/7.4/include
LIBDIR=/usr/opt/daq/7.4/lib
VMELIBRARY=-L/usr/opt/daq/7.4/lib -lbtp
VMELIBRARYHEADERS=-I/usr/opt/daq/7.4/include
spectrodaq_conf_dir=/usr/opt/spectrodaq/bin
CAMAC=-DCESCAMAC
#
#  Makefile to build a readout program given the stuff in the standard
#  skeleton.
#

SPECTRO_FLAGS=$(shell $(spectrodaq_conf_dir)/spectrodaq-conf --cflags)
SPECTRO_LDFLAGS=$(shell $(spectrodaq_conf_dir)/spectrodaq-conf --libs)

CC = gcc




LDFLAGS=-L$(LIBDIR) -lReadout -lException $(VMELIBRARY) $(SPECTRO_LDFLAGS) \
	-lTclPlus -ltk -ltcl -lm -Wl,"-rpath=$(LIBDIR)"

CXXFLAGS = -ggdb -c -D__UNIX__ $(SPECTRO_FLAGS) -I$(INCLUDEDIR) \
	-I$(VMELIBRARYHEADERS) $(CAMAC) -DVME -I/usr/include/tcl \
	-I. 


CPP = g++ $(CXXFLAGS)

.cpp.o:
	$(CPP) $<

#  Last one >was< CScalerModule.o


PROGOBJS=ReadoutMain.o skeleton.o  \
CBoolConfigParam.o \
CCAENV775.o \
CCAENV775Creator.o \
CCAENV785.o \
CCAENV785Creator.o \
CConfigurationParameter.o \
CDigitizerDictionary.o \
CDigitizerModule.o \
CIntArrayParam.o \
CIntConfigParam.o \
CStringArrayparam.o \
CStringConfigParam.o \
CModuleCommand.o \
CModuleCreator.o \
CReadOrder.o \
CScalerBank.o \
CScalerModule.o \
CNullBusy.o  CCAENModule.o  \
CCAENV792.o CCAENV792Creator.o \
CCAENV830.o CCAENV830Module.o CCAENV830Creator.o




all : Program

Program: $(PROGOBJS)
	g++ -o Readout $(PROGOBJS) $(LDFLAGS)

ReadoutMain.o: ReadoutMain.cpp
	$(CPP)  $<
skeleton.o: skeleton.cpp
	$(CPP)  $<

clean:
	rm -f $(PROGOBJS)
	rm -f Readout


depend:
	makedepend -Y. *.cpp

















# DO NOT DELETE

CBoolConfigParam.o: CBoolConfigParam.h CConfigurationParameter.h
CCAENModule.o: CCAENModule.h CDigitizerModule.h CConfigurationParameter.h
CCAENModule.o: CIntConfigParam.h CBoolConfigParam.h CIntArrayParam.h
CCAENTrigger.o: CCAENTrigger.h
CCAENV775.o: CCAENV775.h CDigitizerModule.h CConfigurationParameter.h
CCAENV775.o: CCAENModule.h CIntConfigParam.h CIntArrayParam.h
CCAENV775.o: CBoolConfigParam.h
CCAENV775Creator.o: CCAENV775Creator.h CModuleCreator.h CCAENV775.h
CCAENV775Creator.o: CDigitizerModule.h CConfigurationParameter.h
CCAENV775Creator.o: CCAENModule.h
CCAENV785.o: CCAENV785.h CDigitizerModule.h CConfigurationParameter.h
CCAENV785.o: CCAENModule.h CIntConfigParam.h CBoolConfigParam.h
CCAENV785.o: CIntArrayParam.h
CCAENV785Creator.o: CCAENV785Creator.h CModuleCreator.h CDigitizerModule.h
CCAENV785Creator.o: CConfigurationParameter.h CCAENV785.h CCAENModule.h
CCAENV792.o: CCAENV792.h CDigitizerModule.h CConfigurationParameter.h
CCAENV792.o: CCAENModule.h CIntConfigParam.h CBoolConfigParam.h
CCAENV792.o: CIntArrayParam.h
CCAENV792Creator.o: CCAENV792Creator.h CModuleCreator.h CCAENV792.h
CCAENV792Creator.o: CDigitizerModule.h CConfigurationParameter.h
CCAENV792Creator.o: CCAENModule.h
CCAENV830.o: CCAENV830.h CCAENV820Registers.h
CCAENV830Creator.o: CCAENV830Creator.h CModuleCreator.h CCAENV830Module.h
CCAENV830Creator.o: CDigitizerModule.h CConfigurationParameter.h
CCAENV830Module.o: CCAENV830Module.h CDigitizerModule.h
CCAENV830Module.o: CConfigurationParameter.h CCAENV830.h CBoolConfigParam.h
CCAENV830Module.o: CIntConfigParam.h CIntArrayParam.h
CConfigurationParameter.o: CConfigurationParameter.h
CDigitizerDictionary.o: CDigitizerDictionary.h CDigitizerModule.h
CDigitizerDictionary.o: CConfigurationParameter.h
CDigitizerModule.o: CDigitizerModule.h CConfigurationParameter.h
CDigitizerModule.o: CIntConfigParam.h CIntArrayParam.h CBoolConfigParam.h
CDigitizerModule.o: CStringConfigParam.h CStringArrayparam.h
CIntArrayParam.o: CIntArrayParam.h
CIntConfigParam.o: CIntConfigParam.h
CModuleCommand.o: CModuleCommand.h CDigitizerDictionary.h CModuleCreator.h
CModuleCommand.o: CDigitizerModule.h CConfigurationParameter.h CReadOrder.h
CModuleCreator.o: CModuleCreator.h CDigitizerModule.h
CModuleCreator.o: CConfigurationParameter.h
CNullBusy.o: CNullBusy.h
CReadOrder.o: CReadOrder.h CModuleCommand.h CDigitizerDictionary.h
CReadOrder.o: CDigitizerModule.h CConfigurationParameter.h
CScalerBank.o: CScalerBank.h CReadOrder.h CDigitizerDictionary.h
CScalerBank.o: CScalerModule.h CDigitizerModule.h CConfigurationParameter.h
CScalerModule.o: CScalerModule.h CDigitizerModule.h CConfigurationParameter.h
CStringArrayparam.o: CStringArrayparam.h
CStringConfigParam.o: CStringConfigParam.h
CTriggerCommand.o: CTriggerCommand.h CCAENModule.h CDigitizerModule.h
CTriggerCommand.o: CConfigurationParameter.h CCAENTrigger.h
CTriggerCommand.o: CDigitizerDictionary.h
skeleton.o: CNullBusy.h CDigitizerDictionary.h CReadOrder.h CModuleCommand.h
skeleton.o: CCAENV785Creator.h CModuleCreator.h CCAENV792Creator.h
skeleton.o: CCAENV775Creator.h CCAENV830.h CCAENV830Creator.h
skeleton.o: CCAENV830Module.h CDigitizerModule.h CConfigurationParameter.h
