/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  /usr/bin/gengetopt --output-dir=. --file=filterargs --unamed-opts=OPTIONS 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "filterargs.h"

const char *gengetopt_args_info_purpose = "Provides ability to insert experiment specific filter into data stream";

const char *gengetopt_args_info_usage = "Usage: NSCLDaq Filter [OPTIONS]... [OPTIONS]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                   Print help and exit",
  "  -V, --version                Print version and exit",
  "  -s, --source=STRING          URL of source. Specifies either a ring buffer,\n                                 file, or - for stdin  (default=`-')",
  "  -d, --sink=STRING            URL of sink. Specifies either a ring buffer,\n                                 file, or - for stdout  (default=`-')",
  "  -m, --skip=INT               Number of items to skip before dumping",
  "  -c, --count=INT              Number of items to process before exiting",
  "  -S, --sample=STRING          List of item types to sample",
  "  -e, --exclude=STRING         List of item types to remove from data stream",
  "  -o, --oneshot                Record one run and exit, making synchronization\n                                 files",
  "  -n, --number-of-sources=INT  Number of data sources being built\n                                 (default=`1')",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->source_given = 0 ;
  args_info->sink_given = 0 ;
  args_info->skip_given = 0 ;
  args_info->count_given = 0 ;
  args_info->sample_given = 0 ;
  args_info->exclude_given = 0 ;
  args_info->oneshot_given = 0 ;
  args_info->number_of_sources_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->source_arg = gengetopt_strdup ("-");
  args_info->source_orig = NULL;
  args_info->sink_arg = gengetopt_strdup ("-");
  args_info->sink_orig = NULL;
  args_info->skip_orig = NULL;
  args_info->count_orig = NULL;
  args_info->sample_arg = NULL;
  args_info->sample_orig = NULL;
  args_info->exclude_arg = NULL;
  args_info->exclude_orig = NULL;
  args_info->number_of_sources_arg = 1;
  args_info->number_of_sources_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->source_help = gengetopt_args_info_help[2] ;
  args_info->sink_help = gengetopt_args_info_help[3] ;
  args_info->skip_help = gengetopt_args_info_help[4] ;
  args_info->count_help = gengetopt_args_info_help[5] ;
  args_info->sample_help = gengetopt_args_info_help[6] ;
  args_info->exclude_help = gengetopt_args_info_help[7] ;
  args_info->oneshot_help = gengetopt_args_info_help[8] ;
  args_info->number_of_sources_help = gengetopt_args_info_help[9] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->source_arg));
  free_string_field (&(args_info->source_orig));
  free_string_field (&(args_info->sink_arg));
  free_string_field (&(args_info->sink_orig));
  free_string_field (&(args_info->skip_orig));
  free_string_field (&(args_info->count_orig));
  free_string_field (&(args_info->sample_arg));
  free_string_field (&(args_info->sample_orig));
  free_string_field (&(args_info->exclude_arg));
  free_string_field (&(args_info->exclude_orig));
  free_string_field (&(args_info->number_of_sources_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->source_given)
    write_into_file(outfile, "source", args_info->source_orig, 0);
  if (args_info->sink_given)
    write_into_file(outfile, "sink", args_info->sink_orig, 0);
  if (args_info->skip_given)
    write_into_file(outfile, "skip", args_info->skip_orig, 0);
  if (args_info->count_given)
    write_into_file(outfile, "count", args_info->count_orig, 0);
  if (args_info->sample_given)
    write_into_file(outfile, "sample", args_info->sample_orig, 0);
  if (args_info->exclude_given)
    write_into_file(outfile, "exclude", args_info->exclude_orig, 0);
  if (args_info->oneshot_given)
    write_into_file(outfile, "oneshot", 0, 0 );
  if (args_info->number_of_sources_given)
    write_into_file(outfile, "number-of-sources", args_info->number_of_sources_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "source",	1, NULL, 's' },
        { "sink",	1, NULL, 'd' },
        { "skip",	1, NULL, 'm' },
        { "count",	1, NULL, 'c' },
        { "sample",	1, NULL, 'S' },
        { "exclude",	1, NULL, 'e' },
        { "oneshot",	0, NULL, 'o' },
        { "number-of-sources",	1, NULL, 'n' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVs:d:m:c:S:e:on:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 's':	/* URL of source. Specifies either a ring buffer, file, or - for stdin.  */
        
        
          if (update_arg( (void *)&(args_info->source_arg), 
               &(args_info->source_orig), &(args_info->source_given),
              &(local_args_info.source_given), optarg, 0, "-", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "source", 's',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* URL of sink. Specifies either a ring buffer, file, or - for stdout.  */
        
        
          if (update_arg( (void *)&(args_info->sink_arg), 
               &(args_info->sink_orig), &(args_info->sink_given),
              &(local_args_info.sink_given), optarg, 0, "-", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "sink", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Number of items to skip before dumping.  */
        
        
          if (update_arg( (void *)&(args_info->skip_arg), 
               &(args_info->skip_orig), &(args_info->skip_given),
              &(local_args_info.skip_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "skip", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Number of items to process before exiting.  */
        
        
          if (update_arg( (void *)&(args_info->count_arg), 
               &(args_info->count_orig), &(args_info->count_given),
              &(local_args_info.count_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "count", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* List of item types to sample.  */
        
        
          if (update_arg( (void *)&(args_info->sample_arg), 
               &(args_info->sample_orig), &(args_info->sample_given),
              &(local_args_info.sample_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "sample", 'S',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* List of item types to remove from data stream.  */
        
        
          if (update_arg( (void *)&(args_info->exclude_arg), 
               &(args_info->exclude_orig), &(args_info->exclude_given),
              &(local_args_info.exclude_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "exclude", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Record one run and exit, making synchronization files.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->oneshot_given),
              &(local_args_info.oneshot_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "oneshot", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Number of data sources being built.  */
        
        
          if (update_arg( (void *)&(args_info->number_of_sources_arg), 
               &(args_info->number_of_sources_orig), &(args_info->number_of_sources_given),
              &(local_args_info.number_of_sources_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "number-of-sources", 'n',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
